# -*- coding: utf-8 -*-
"""analise_latrocinio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUBscVFgyvw2sDHdMp2Qjo7Z5TpaLg2n
"""

from google.colab import files
import pandas as pd

# Faz upload do arquivo do seu PC
uploaded = files.upload()

# Pega o nome do arquivo enviado
file_path = list(uploaded.keys())[0]

import pandas as pd

# Ler apenas as planilha 2024
dt = pd.read_excel(file_path)

print(dt)

ranking = dt['Natureza'].value_counts()
print(ranking)

ranking = dt['Município'].value_counts()
print(ranking.head(10))

# Latrocinios de Curitiba comparado ao interior

# Criar uma coluna agrupando Curitiba x outros
dt['Grupo'] = dt['Município'].apply(lambda x: 'CURITIBA' if x == 'CURITIBA' else 'INTERIOR')

# Contar ocorrências por grupo
ranking_agrupado = dt['Grupo'].value_counts()
print(ranking_agrupado)

def calcular_indice_latrocinios(dt):
    """
    Calcula o índice de latrocínios por 100 mil habitantes para cada Município
    a partir de um DataFrame 'dt' que contém:
    - Município
    - Populacao
    (os registros representam ocorrências de crimes individuais)
    """

    # Garante que as colunas necessárias existam
    colunas_necessarias = {'Município', 'Populacao'}
    if not colunas_necessarias.issubset(dt.columns):
        raise ValueError(f"O DataFrame deve conter as colunas: {colunas_necessarias}")

    # Conta quantas ocorrências há por Município (ranking)
    ranking = dt['Município'].value_counts().reset_index(name='Crime')
    ranking.columns = ['Município', 'Crime']

    # Obtém a população de cada Município (removendo duplicadas)
    pop = dt[['Município', 'Populacao']].drop_duplicates()

    # Junta população com o ranking
    df = ranking.merge(pop, on='Município', how='left')

    # Calcula o índice por 100 mil habitantes
    df['Indice (por 100 mil hab)'] = (df['Crime'] / df['Populacao']) * 100000

    # Ordena do maior para o menor
    resultado = df.sort_values(by='Indice (por 100 mil hab)', ascending=False).reset_index(drop=True)

    return resultado


resultado = calcular_indice_latrocinios(dt)
print(resultado.head(20))

# ranking cidade grandes

resultado = calcular_indice_latrocinios(dt)
print(resultado.tail(5))